function Events() {
    var spreadsheet = SpreadsheetApp.getActive();
    var currentCell = spreadsheet.getCurrentCell().offset(967, 0);
    spreadsheet.getCurrentCell().offset(0, 0, 968, 1).activate();
    spreadsheet.setCurrentCell(currentCell);
    spreadsheet.getCurrentCell().offset(-967, 0).copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
  };
  
  function FixRanks() {
    var spreadsheet = SpreadsheetApp.getActive();
    spreadsheet.getRange('F9:F976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('F976'));
    spreadsheet.getRange('F9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('H9:H976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('H976'));
    spreadsheet.getRange('H9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('J9:K976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('K976'));
    spreadsheet.getRange('J9:K9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('M9:N976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('N976'));
    spreadsheet.getRange('M9:N9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('P9:Q976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('Q976'));
    spreadsheet.getRange('P9:Q9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('S9:T976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('T976'));
    spreadsheet.getRange('S9:T9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('V9:W976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('W976'));
    spreadsheet.getRange('V9:W9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('Y9:Z976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('Z976'));
    spreadsheet.getRange('Y9:Z9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('AB9:AC976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('AC976'));
    spreadsheet.getRange('AB9:AC9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
  };
  
  function Sort() {
    var spreadsheet = SpreadsheetApp.getActive();
    spreadsheet.getRange('C8').activate();
    spreadsheet.getActiveSheet().getFilter().sort(3, true);
  };
  
  function Sort1() {
    var spreadsheet = SpreadsheetApp.getActive();
    spreadsheet.getRange('C8').activate();
    spreadsheet.getActiveSheet().getFilter().sort(3, true);
    spreadsheet.getRange('F9:F976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('F976'));
    spreadsheet.getRange('F9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('H9:H976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('H976'));
    spreadsheet.getRange('H9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('J9:K976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('K976'));
    spreadsheet.getRange('J9:K9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('M9:N976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('N976'));
    spreadsheet.getRange('M9:N9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('P9:Q976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('Q976'));
    spreadsheet.getRange('P9:Q9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('S9:T976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('T976'));
    spreadsheet.getRange('S9:T9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('V9:W976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('W976'));
    spreadsheet.getRange('V9:W9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('Y9:Z976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('Z976'));
    spreadsheet.getRange('Y9:Z9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('AB9:AC976').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('AC976'));
    spreadsheet.getRange('AB9:AC9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
  };
  
  function FixRanksUpdated() {
    var spreadsheet = SpreadsheetApp.getActive();
    spreadsheet.getRange('C8').activate();
    spreadsheet.getActiveSheet().getFilter().sort(3, true);
    spreadsheet.getRange('F9:F1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('F1476'));
    spreadsheet.getRange('F9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('H9:H1476').activate();
    spreadsheet.getRange('H9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('J9:K1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('K1476'));
    spreadsheet.getRange('J9:K9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('M9:N1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('N1476'));
    spreadsheet.getRange('M9:N9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('P9:Q1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('Q1476'));
    spreadsheet.getRange('P9:Q9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('S9:T1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('T1476'));
    spreadsheet.getRange('S1476:T1476').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('V9:W1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('W1476'));
    spreadsheet.getRange('V1476:W1476').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('Y9:Z1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('Z1476'));
    spreadsheet.getRange('Y9:Z9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('AB9:AC1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('AC1476'));
    spreadsheet.getRange('AB9:AC9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
  };
  
  function UpdateRanks() {
    var spreadsheet = SpreadsheetApp.getActive();
    spreadsheet.getRange('D8').activate();
    spreadsheet.getActiveSheet().getFilter().sort(3, true);
    spreadsheet.getRange('H9:H1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('H1476'));
    spreadsheet.getRange('H9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('J9:J1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('J1476'));
    spreadsheet.getRange('J9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('L9:M1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('M1476'));
    spreadsheet.getRange('L9:M9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('O9:P1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('P1476'));
    spreadsheet.getRange('O9:P9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('R9:S1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('S1476'));
    spreadsheet.getRange('R9:S9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('U9:V1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('V1476'));
    spreadsheet.getRange('U9:V9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('X9:Y1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('Y1476'));
    spreadsheet.getRange('X9:Y9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('AA9:AB1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('AB1476'));
    spreadsheet.getRange('AA9:AB9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('AD9:AE1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('AE1476'));
    spreadsheet.getRange('AD9:AE9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('D:D').activate();
    spreadsheet.getActiveSheet().hideColumns(spreadsheet.getActiveRange().getColumn(), spreadsheet.getActiveRange().getNumColumns());
    spreadsheet.getRange('E:E').activate();
  };
  
  function UpdateRankOrder() {
    var spreadsheet = SpreadsheetApp.getActive();
    spreadsheet.getRange('8:8').activate();
    spreadsheet.getActiveSheet().showRows(8, 1);
    spreadsheet.getRange('D8').activate();
    spreadsheet.getActiveSheet().getFilter().sort(4, true);
    spreadsheet.getRange('H9:H1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('H1476'));
    spreadsheet.getRange('H9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('J9:J1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('J1476'));
    spreadsheet.getRange('J9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('L9:M1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('M1476'));
    spreadsheet.getRange('L9:M9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('O9:P1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('P1476'));
    spreadsheet.getRange('O9:P9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('R9:S1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('R1476'));
    spreadsheet.getRange('R9:S9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('U9:V1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('V1476'));
    spreadsheet.getRange('U9:V9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('X9:Y1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('Y1476'));
    spreadsheet.getRange('X9:Y9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('AA9:AB1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('AB1476'));
    spreadsheet.getRange('AA9:AB9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('AD9:AE1476').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('AE1476'));
    spreadsheet.getRange('AD9:AE9').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
    spreadsheet.getRange('9:9').activate();
    spreadsheet.getActiveSheet().hideRows(spreadsheet.getActiveRange().getRow(), spreadsheet.getActiveRange().getNumRows());
    spreadsheet.getRange('10:10').activate();
    spreadsheet.getRange('D:D').activate();
    spreadsheet.getActiveSheet().hideColumns(spreadsheet.getActiveRange().getColumn(), spreadsheet.getActiveRange().getNumColumns());
    spreadsheet.getRange('E:E').activate();
  };
  
  
  function concat() {
    var spreadsheet = SpreadsheetApp.getActive();
    spreadsheet.getRange('A10:H672').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('G672'));
    spreadsheet.getRange('A10:H10').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
  };
  
  function cnm() {
    var spreadsheet = SpreadsheetApp.getActive();
    spreadsheet.getRange('J2:L996').activate();
    spreadsheet.setCurrentCell(spreadsheet.getRange('L996'));
    spreadsheet.getRange('J2:L2').copyTo(spreadsheet.getActiveRange(), SpreadsheetApp.CopyPasteType.PASTE_NORMAL, false);
  };